dist: xenial
language: python
python: 3.7
addons:
  update: true
  apt:
    packages:
    - uuid-dev
    - nasm
    - iasl
git:
  depth: 1
  submodules: false
env:
  global:
    - MAKEFLAGS="-j $(nproc)"
install:
  - git submodule update --init --recursive --depth 1
stages:
  - compile
jobs:
  include:
    - stage: compile
      name: "IA32"
      script: cd ./edk2 && ./OvmfPkg/build.sh -n $(nproc) -D HTTP_BOOT_ENABLE -D TLS_ENABLE -b RELEASE -a IA32
    - name: "IA32X64"
      script: cd ./edk2 && ./OvmfPkg/build.sh -n $(nproc) -D HTTP_BOOT_ENABLE -D TLS_ENABLE -b RELEASE -a IA32 -a X64
    - name: "X64"
      script: cd ./edk2 && ./OvmfPkg/build.sh -n $(nproc) -D HTTP_BOOT_ENABLE -D TLS_ENABLE -b RELEASE -a X64
