dist: xenial
language: c
addons:
  apt:
    packages:
    - qemu
    - uuid-dev
    - nasm
    - iasl
    - python3-setuptools
stages:
  - compile
jobs:
  include:
    - stage: compile
      name: "IA32"
      script: cd ./edk2 && ./OvmfPkg/build.sh -n $(nproc) -D HTTP_BOOT_ENABLE -D TLS_ENABLE -b RELEASE -a IA32
    - name: "IA32X64"
      script: cd ./edk2 && ./OvmfPkg/build.sh -n $(nproc) -D HTTP_BOOT_ENABLE -D TLS_ENABLE -b RELEASE -a IA32 -a X64
    - name: "X64"
      script: cd ./edk2 && ./OvmfPkg/build.sh -n $(nproc) -D HTTP_BOOT_ENABLE -D TLS_ENABLE -b RELEASE -a X64
